-- Migration: 20260301_create_ssr_panel_tables.sql
-- Creates all tables for the SSR consumer panel tool system.
--
-- Prerequisites:
--   - update_updated_at_column() function must already exist (defined in 20251104000000_create_discord_workflow_system.sql)
--
-- Post-migration step:
--   - Run: python -m scripts.seed_anchor_embeddings
--     This embeds all anchor statements in ssr_anchor_set using text-embedding-3-small.
--     No ssr_panel_run calls will succeed until this is done.
--
-- Tables created (in dependency order):
--   1. ssr_panel          — panel definitions (owner, demographics, psychographics)
--   2. ssr_persona        — generated synthetic consumer personas
--   3. ssr_run            — SSR pipeline executions (one per stimulus)
--   4. ssr_response       — free-text persona reactions to stimulus
--   5. ssr_score          — per-persona per-dimension Likert scores
--   6. ssr_anchor_set     — Likert anchor statements (seed table, read-only by tools)
--
-- See: loops/dec-oc-ssr-tools-reverse/tool-spec/data-model/supabase-schema.md for full column docs.


-- ─────────────────────────────────────────────────────────────────────────────
-- Table 1: ssr_panel
-- Panel definitions: demographic/psychographic targets with generated personas.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE ssr_panel (
    id                   UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    discord_id           TEXT        NOT NULL,
    panel_name           TEXT        NOT NULL,
    product_category     TEXT        NOT NULL,
    demographics         JSONB       NOT NULL DEFAULT '{}'::jsonb,
    psychographics       JSONB,
    panel_size           INTEGER     NOT NULL,
    actual_size          INTEGER,
    custom_instructions  TEXT,
    status               TEXT        NOT NULL DEFAULT 'generating',
    CONSTRAINT ssr_panel_status_valid
        CHECK (status IN ('generating', 'ready', 'partial', 'failed')),
    created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE ssr_panel IS 'SSR consumer panel definitions: demographic/psychographic targets with generated synthetic personas';
COMMENT ON COLUMN ssr_panel.discord_id IS 'Discord user ID (snowflake) of the panel owner, stored as TEXT';
COMMENT ON COLUMN ssr_panel.demographics IS 'Serialized PersonaDemographics: age_min, age_max, genders, locations, income_brackets, education_levels, languages';
COMMENT ON COLUMN ssr_panel.psychographics IS 'Optional serialized PersonaPsychographics: interests, values, lifestyle_descriptors, media_consumption. NULL if omitted.';
COMMENT ON COLUMN ssr_panel.panel_size IS 'Requested number of personas (5–50 per Pydantic validation)';
COMMENT ON COLUMN ssr_panel.actual_size IS 'Number of successfully generated personas. NULL while generating. May be less than panel_size on partial generation.';
COMMENT ON COLUMN ssr_panel.status IS 'generating: in progress; ready: all personas generated; partial: ≥50% generated; failed: <50% generated (panel not usable, should be deleted)';

CREATE TRIGGER ssr_panel_updated_at
    BEFORE UPDATE ON ssr_panel
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE INDEX IF NOT EXISTS idx_ssr_panel_discord_id ON ssr_panel(discord_id);
CREATE INDEX IF NOT EXISTS idx_ssr_panel_created_at ON ssr_panel(created_at DESC);


-- ─────────────────────────────────────────────────────────────────────────────
-- Table 2: ssr_persona
-- Synthetic consumer personas generated by Claude Haiku for a panel.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE ssr_persona (
    id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    panel_id        UUID        NOT NULL REFERENCES ssr_panel(id) ON DELETE CASCADE,
    persona_index   INTEGER     NOT NULL,
    name            TEXT        NOT NULL,
    age             INTEGER     NOT NULL,
    CONSTRAINT ssr_persona_age_valid
        CHECK (age >= 18 AND age <= 99),
    location        TEXT        NOT NULL,
    occupation      TEXT        NOT NULL,
    income_bracket  TEXT        NOT NULL,
    CONSTRAINT ssr_persona_income_bracket_valid
        CHECK (income_bracket IN ('low', 'lower_middle', 'middle', 'upper_middle', 'high')),
    education       TEXT        NOT NULL,
    CONSTRAINT ssr_persona_education_valid
        CHECK (education IN ('high_school', 'some_college', 'bachelors', 'graduate', 'postgraduate')),
    summary         TEXT        NOT NULL,
    full_profile    TEXT        NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ssr_persona_panel_index_unique UNIQUE (panel_id, persona_index)
);

COMMENT ON TABLE ssr_persona IS 'Synthetic consumer personas generated by Claude Haiku for a panel. Reused across multiple runs.';
COMMENT ON COLUMN ssr_persona.persona_index IS '1-based ordinal position within the panel. Unique per panel.';
COMMENT ON COLUMN ssr_persona.income_bracket IS 'Relative income bracket in persona''s country: low, lower_middle, middle, upper_middle, high';
COMMENT ON COLUMN ssr_persona.education IS 'Highest completed education: high_school, some_college, bachelors, graduate, postgraduate';
COMMENT ON COLUMN ssr_persona.summary IS '2–3 sentence human-readable display summary shown in panel_create tool output';
COMMENT ON COLUMN ssr_persona.full_profile IS 'Complete labeled-section Claude Haiku output. Used as system prompt content when inhabiting persona during ssr_panel_run.';

CREATE INDEX IF NOT EXISTS idx_ssr_persona_panel_id ON ssr_persona(panel_id);


-- ─────────────────────────────────────────────────────────────────────────────
-- Table 3: ssr_run
-- A single SSR pipeline execution: one stimulus tested against all panel personas.
-- Contains the stimulus (denormalized for query efficiency — no separate ssr_stimulus table).
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE ssr_run (
    id                    UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    panel_id              UUID        NOT NULL REFERENCES ssr_panel(id) ON DELETE CASCADE,
    discord_id            TEXT        NOT NULL,
    run_label             TEXT        NOT NULL,
    stimulus              TEXT        NOT NULL,
    stimulus_type         TEXT        NOT NULL,
    CONSTRAINT ssr_run_stimulus_type_valid
        CHECK (stimulus_type IN (
            'ad_copy',
            'headline',
            'tagline',
            'product_concept',
            'brand_message',
            'campaign_theme',
            'influencer_pitch',
            'pricing_message',
            'packaging_description',
            'social_caption'
        )),
    evaluation_dimensions TEXT[]      NOT NULL DEFAULT '{}',
    status                TEXT        NOT NULL DEFAULT 'pending',
    CONSTRAINT ssr_run_status_valid
        CHECK (status IN ('pending', 'running', 'completed', 'failed')),
    personas_scored       INTEGER,
    dimension_means       JSONB,
    started_at            TIMESTAMPTZ,
    completed_at          TIMESTAMPTZ,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE ssr_run IS 'A single SSR pipeline execution: one stimulus tested against all personas in a panel';
COMMENT ON COLUMN ssr_run.discord_id IS 'Denormalized panel owner for fast ownership checks without joining ssr_panel';
COMMENT ON COLUMN ssr_run.stimulus IS 'Full text of the marketing asset being tested (up to 4000 chars, enforced by Pydantic)';
COMMENT ON COLUMN ssr_run.stimulus_type IS 'Category: ad_copy, headline, tagline, product_concept, brand_message, campaign_theme, influencer_pitch, pricing_message, packaging_description, social_caption';
COMMENT ON COLUMN ssr_run.evaluation_dimensions IS 'Array of dimension names evaluated in this run, e.g. {purchase_intent,message_clarity,overall_appeal}';
COMMENT ON COLUMN ssr_run.status IS 'pending: created; running: pipeline executing; completed: results stored; failed: pipeline errored';
COMMENT ON COLUMN ssr_run.personas_scored IS 'Count of personas that produced scoreable responses. NULL until run completes.';
COMMENT ON COLUMN ssr_run.dimension_means IS 'Quick-access dict of dimension_name → mean_score, e.g. {"purchase_intent": 3.85}. NULL until run completes.';
COMMENT ON COLUMN ssr_run.started_at IS 'When the SSR pipeline began executing. NULL while status=pending.';
COMMENT ON COLUMN ssr_run.completed_at IS 'When the pipeline finished (success or failure). NULL until status=completed or failed.';

CREATE TRIGGER ssr_run_updated_at
    BEFORE UPDATE ON ssr_run
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE INDEX IF NOT EXISTS idx_ssr_run_panel_id ON ssr_run(panel_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ssr_run_discord_id ON ssr_run(discord_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ssr_run_status ON ssr_run(status) WHERE status IN ('pending', 'running');


-- ─────────────────────────────────────────────────────────────────────────────
-- Table 4: ssr_response
-- Free-text consumer reactions elicited from each persona for a panel run.
-- One row per (run, persona) pair.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE ssr_response (
    id             UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    run_id         UUID        NOT NULL REFERENCES ssr_run(id) ON DELETE CASCADE,
    persona_id     UUID        NOT NULL REFERENCES ssr_persona(id) ON DELETE CASCADE,
    response_text  TEXT        NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ssr_response_run_persona_unique UNIQUE (run_id, persona_id)
);

COMMENT ON TABLE ssr_response IS 'Free-text consumer reactions elicited from each persona for a panel run. One row per (run, persona).';
COMMENT ON COLUMN ssr_response.response_text IS 'Raw Claude Haiku output when inhabiting the persona and reacting to the stimulus. Not parsed or truncated. Typically 300–1800 characters.';

CREATE INDEX IF NOT EXISTS idx_ssr_response_run_id ON ssr_response(run_id);
CREATE INDEX IF NOT EXISTS idx_ssr_response_persona_run ON ssr_response(persona_id, run_id);


-- ─────────────────────────────────────────────────────────────────────────────
-- Table 5: ssr_score
-- Per-persona per-dimension Likert scores. One row per (response, dimension).
-- run_id and persona_id are denormalized from ssr_response for fast run-level queries.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE ssr_score (
    id                  UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    response_id         UUID        NOT NULL REFERENCES ssr_response(id) ON DELETE CASCADE,
    run_id              UUID        NOT NULL REFERENCES ssr_run(id) ON DELETE CASCADE,
    persona_id          UUID        NOT NULL REFERENCES ssr_persona(id) ON DELETE CASCADE,
    dimension           TEXT        NOT NULL,
    hard_score          INTEGER     NOT NULL,
    CONSTRAINT ssr_score_hard_score_valid
        CHECK (hard_score >= 1 AND hard_score <= 5),
    weighted_score      FLOAT8      NOT NULL,
    similarities        JSONB       NOT NULL DEFAULT '{}'::jsonb,
    response_embedding  FLOAT8[],
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ssr_score_response_dimension_unique UNIQUE (response_id, dimension)
);

COMMENT ON TABLE ssr_score IS 'Per-persona per-dimension Likert scores. One row per (response, dimension). run_id and persona_id are denormalized for efficient run-level queries.';
COMMENT ON COLUMN ssr_score.run_id IS 'Denormalized run_id from ssr_response.run_id for fast SELECT * WHERE run_id = $1 without join';
COMMENT ON COLUMN ssr_score.persona_id IS 'Denormalized persona_id from ssr_response.persona_id for fast persona-name joins';
COMMENT ON COLUMN ssr_score.dimension IS 'Evaluation dimension name, e.g. purchase_intent, message_clarity. One of the 10 EvaluationDimension values.';
COMMENT ON COLUMN ssr_score.hard_score IS 'Integer Likert score 1–5: argmax of cosine similarities across all 5 anchor embeddings';
COMMENT ON COLUMN ssr_score.weighted_score IS 'Continuous score 1.0–5.0: softmax-weighted mean of anchor scale points using cosine similarities as weights';
COMMENT ON COLUMN ssr_score.similarities IS 'Dict of scale_point → cosine_similarity, e.g. {"1": 0.182, "2": 0.241, "3": 0.389, "4": 0.712, "5": 0.834}. Keys are strings (JSONB requirement).';
COMMENT ON COLUMN ssr_score.response_embedding IS 'Optional 1536-dim float32 embedding of response_text (text-embedding-3-small). NULL by default. Stored for future re-scoring without API calls. 12 KB per row.';

CREATE INDEX IF NOT EXISTS idx_ssr_score_run_id ON ssr_score(run_id);
CREATE INDEX IF NOT EXISTS idx_ssr_score_response_id ON ssr_score(response_id);


-- ─────────────────────────────────────────────────────────────────────────────
-- Table 6: ssr_anchor_set
-- Pre-defined Likert anchor statements per evaluation dimension.
-- READ-ONLY for tool handlers. Populated by scripts/seed_anchor_embeddings.py.
--
-- Seed data is inserted below (anchor_embedding starts NULL; script fills it in).
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE ssr_anchor_set (
    id                UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    dimension_name    TEXT        NOT NULL,
    scale_point       INTEGER     NOT NULL,
    CONSTRAINT ssr_anchor_set_scale_point_valid
        CHECK (scale_point >= 1 AND scale_point <= 5),
    anchor_text       TEXT        NOT NULL,
    anchor_embedding  FLOAT8[],
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ssr_anchor_set_dimension_point_unique UNIQUE (dimension_name, scale_point)
);

COMMENT ON TABLE ssr_anchor_set IS 'Pre-defined Likert anchor statements per evaluation dimension, with pre-computed embeddings. Read-only for tool handlers. Populated by scripts/seed_anchor_embeddings.py.';
COMMENT ON COLUMN ssr_anchor_set.dimension_name IS 'Evaluation dimension: purchase_intent, brand_favorability, message_clarity, emotional_response, personal_relevance, uniqueness, trust_credibility, value_perception, share_worthiness, overall_appeal';
COMMENT ON COLUMN ssr_anchor_set.scale_point IS 'Likert scale point 1–5 this anchor represents (1=strongly negative, 5=strongly positive)';
COMMENT ON COLUMN ssr_anchor_set.anchor_text IS 'Naturalistic English sentence describing a consumer attitude at this scale point. Embedded and compared against persona response embeddings.';
COMMENT ON COLUMN ssr_anchor_set.anchor_embedding IS 'Pre-computed 1536-dim float32 embedding using text-embedding-3-small. NULL until seed script runs. ssr_panel_run fails if NULL for any requested dimension.';

CREATE INDEX IF NOT EXISTS idx_ssr_anchor_set_dimension ON ssr_anchor_set(dimension_name);


-- ─────────────────────────────────────────────────────────────────────────────
-- Seed Data: ssr_anchor_set
-- All 50 anchor statements (10 dimensions × 5 scale points).
-- anchor_embedding is NULL here — populated by scripts/seed_anchor_embeddings.py.
-- See tool-spec/pipeline/anchor-statements.md for full specification with rationale.
-- ─────────────────────────────────────────────────────────────────────────────

INSERT INTO ssr_anchor_set (dimension_name, scale_point, anchor_text) VALUES

-- Dimension 1: purchase_intent
-- Measures likelihood to purchase, try, or take action to acquire.
('purchase_intent', 1, 'I would not buy this under any circumstances and would actively avoid it.'),
('purchase_intent', 2, 'I am unlikely to buy this — it does not appeal to me enough to spend my money.'),
('purchase_intent', 3, 'I might consider buying this if the conditions were right, but I''m not drawn to it strongly.'),
('purchase_intent', 4, 'I would probably buy this — it appeals to me and I could see myself picking it up.'),
('purchase_intent', 5, 'I would definitely buy this and would look for it the next time I shop.'),

-- Dimension 2: brand_favorability
-- Measures overall impression and attitude toward the brand after exposure.
('brand_favorability', 1, 'This makes me think worse of the brand — it feels off-putting or inconsistent with what I expect.'),
('brand_favorability', 2, 'This does not improve my impression of the brand — I feel indifferent or slightly negative.'),
('brand_favorability', 3, 'This does not change how I feel about the brand — my impression is the same as before.'),
('brand_favorability', 4, 'This gives me a better impression of the brand — it feels authentic and aligned with my values.'),
('brand_favorability', 5, 'This makes me think much more highly of the brand — I feel genuinely positive and more loyal.'),

-- Dimension 3: message_clarity
-- Measures how easily the communication is understood.
('message_clarity', 1, 'I have no idea what this is trying to say — the message is completely unclear or confusing.'),
('message_clarity', 2, 'The message is somewhat unclear — I had to work to understand what they''re trying to communicate.'),
('message_clarity', 3, 'I understand what this is saying, but it took me a moment — the communication is average.'),
('message_clarity', 4, 'The message is clear and easy to follow — I understood immediately what they were communicating.'),
('message_clarity', 5, 'The message is crystal clear and instantly understood — exactly what they wanted to communicate came through perfectly.'),

-- Dimension 4: emotional_response
-- Measures strength of positive emotional engagement (excitement, delight, warmth, inspiration).
('emotional_response', 1, 'This leaves me completely cold — I feel nothing positive and may even feel annoyed or repelled.'),
('emotional_response', 2, 'This generates very little emotional response in me — it fails to connect or engage emotionally.'),
('emotional_response', 3, 'This produces a mild emotional response — I feel slightly interested or mildly positive but not moved.'),
('emotional_response', 4, 'This genuinely engages me emotionally — I feel something real like warmth, excitement, or nostalgia.'),
('emotional_response', 5, 'This moves me deeply — I feel strong positive emotions like joy, inspiration, or heartfelt connection.'),

-- Dimension 5: personal_relevance
-- Measures how much this applies to the respondent's life, situation, or needs.
('personal_relevance', 1, 'This has absolutely nothing to do with my life — it speaks to someone completely different from me.'),
('personal_relevance', 2, 'This doesn''t really speak to me — it''s for someone with a very different lifestyle or situation.'),
('personal_relevance', 3, 'This is somewhat relevant to my life — I can see how it might apply, though it''s not specifically for me.'),
('personal_relevance', 4, 'This speaks directly to my life — it addresses something I actually think about or deal with.'),
('personal_relevance', 5, 'This feels made exactly for me — it addresses my specific situation, needs, and values precisely.'),

-- Dimension 6: uniqueness
-- Measures perceived distinctiveness versus competitors and other options in the category.
('uniqueness', 1, 'This feels completely generic — I''ve seen exactly this before from many other brands and nothing stands out.'),
('uniqueness', 2, 'This is mostly familiar — there are small differences but nothing that really makes it stand apart.'),
('uniqueness', 3, 'This is somewhat distinctive — there are elements that differ from what I usually see, though not dramatically.'),
('uniqueness', 4, 'This stands out from the competition — there is something genuinely different and memorable about it.'),
('uniqueness', 5, 'This is completely fresh and distinctive — I''ve never seen anything quite like it and it truly stands apart.'),

-- Dimension 7: trust_credibility
-- Measures believability, authenticity, and trustworthiness of the claim or brand.
('trust_credibility', 1, 'I find this completely unbelievable and it makes me distrust the brand — it feels manipulative or dishonest.'),
('trust_credibility', 2, 'I am skeptical of this — the claims feel exaggerated or the brand feels inauthentic.'),
('trust_credibility', 3, 'I neither trust nor distrust this — it''s plausible but I don''t have strong confidence in the claims.'),
('trust_credibility', 4, 'I find this credible and believable — the claims feel honest and the brand feels authentic.'),
('trust_credibility', 5, 'I fully trust this — the claims feel completely authentic, honest, and backed by real substance.'),

-- Dimension 8: value_perception
-- Measures perceived value for money — whether the offering seems worth what it costs.
('value_perception', 1, 'This seems like terrible value — the price is way too high for what''s being offered.'),
('value_perception', 2, 'This seems somewhat overpriced — I don''t think it''s worth what they''re asking.'),
('value_perception', 3, 'The value seems fair — the price is about what I''d expect for what''s being offered.'),
('value_perception', 4, 'This seems like good value — I''m getting more than I''d expect for the price.'),
('value_perception', 5, 'This seems like exceptional value — the offer is clearly worth every peso and then some.'),

-- Dimension 9: share_worthiness
-- Measures likelihood to share with friends, family, or social networks.
('share_worthiness', 1, 'I would not share this with anyone — it''s not interesting or relevant enough for me to pass on.'),
('share_worthiness', 2, 'I''m unlikely to share this — it''s not compelling enough to send to my friends or family.'),
('share_worthiness', 3, 'I might share this with one or two people in specific situations, but not broadly.'),
('share_worthiness', 4, 'I would share this with friends or family — it''s something they''d find useful or interesting.'),
('share_worthiness', 5, 'I would immediately share this widely — it''s exactly the kind of content I love to pass on.'),

-- Dimension 10: overall_appeal
-- Measures holistic attractiveness of the marketing asset as a whole.
('overall_appeal', 1, 'This is deeply unappealing — I have a strong negative reaction to the overall execution.'),
('overall_appeal', 2, 'This doesn''t appeal to me — the overall impression is weak or off-putting.'),
('overall_appeal', 3, 'This is neither appealing nor unappealing — it''s average and leaves no strong impression.'),
('overall_appeal', 4, 'This appeals to me — the overall execution is strong and leaves a positive impression.'),
('overall_appeal', 5, 'This is highly appealing — the overall execution is excellent and I have a very strong positive reaction.');
