import { z } from 'zod';
import { PesoSchema, ISODateSchema, TaxYearSchema } from './primitives';
import {
  RegimePathSchema, BalanceDispositionSchema, FormTypeSchema,
  OverpaymentDispositionSchema, TaxpayerTypeSchema, TaxpayerTierSchema,
  TaxpayerClassSchema, FilingPeriodSchema, QuarterOr4Schema, QuarterSchema,
} from './enums';

const RateSchema = z.string();

// InputSummary
const InputSummarySchema = z.object({
  taxYear: TaxYearSchema,
  filingPeriod: FilingPeriodSchema,
  taxpayerType: TaxpayerTypeSchema,
  taxpayerTier: TaxpayerTierSchema,
  grossReceipts: PesoSchema,
  isVatRegistered: z.boolean(),
  incomeType: z.string(),
});

// GrossAggregates
const GrossAggregatesSchema = z.object({
  netGrossReceipts: PesoSchema,
  grossIncome: PesoSchema,
  thresholdBase: PesoSchema,
  eightPctBase: PesoSchema,
  graduatedIncomeBase: PesoSchema,
  ptQuarterlyBase: PesoSchema,
  taxpayerClass: TaxpayerClassSchema,
});

// DeductionBreakdown
const DeductionBreakdownSchema = z.object({
  salaries: PesoSchema,
  employeeBenefits: PesoSchema,
  rent: PesoSchema,
  utilities: PesoSchema,
  communication: PesoSchema,
  officeSupplies: PesoSchema,
  professionalFees: PesoSchema,
  travelTransportation: PesoSchema,
  insurance: PesoSchema,
  interest: PesoSchema,
  taxesLicenses: PesoSchema,
  losses: PesoSchema,
  badDebts: PesoSchema,
  depreciation: PesoSchema,
  charitable: PesoSchema,
  researchDevelopment: PesoSchema,
  entertainmentRepresentation: PesoSchema,
  homeOffice: PesoSchema,
  nolco: PesoSchema,
});

// NolcoEntry (output variant)
const NolcoEntryOutputSchema = z.object({
  lossYear: TaxYearSchema,
  originalLoss: PesoSchema,
  remainingBalance: PesoSchema,
  expiryYear: TaxYearSchema,
});

// PathAResult
const PathAResultSchema = z.object({
  eligible: z.boolean(),
  ptDeductionApplied: PesoSchema,
  bizNti: PesoSchema,
  totalNti: PesoSchema,
  incomeTaxDue: PesoSchema,
  deductionMethod: z.literal('ITEMIZED'),
  pathLabel: z.string(),
  deductionBreakdown: DeductionBreakdownSchema,
  totalDeductions: PesoSchema,
  earCapApplied: PesoSchema,
  interestArbitrageReduction: PesoSchema,
  nolcoRemaining: z.array(NolcoEntryOutputSchema),
});

// PathBResult
const PathBResultSchema = z.object({
  eligible: z.boolean(),
  bizNti: PesoSchema,
  totalNti: PesoSchema,
  incomeTaxDue: PesoSchema,
  osdAmount: PesoSchema,
  deductionMethod: z.literal('OSD'),
  pathLabel: z.string(),
  osdBase: PesoSchema,
});

// PathCResult
const PathCResultSchema = z.object({
  eligible: z.boolean(),
  ineligibleReasons: z.array(z.string()),
  exemptAmount: PesoSchema,
  taxableBase: PesoSchema,
  incomeTaxDue: PesoSchema,
  compensationIt: PesoSchema,
  totalIncomeTax: PesoSchema,
  ptWaived: z.boolean(),
  deductionMethod: z.literal('NONE'),
  pathLabel: z.string(),
});

// RegimeOption
const RegimeOptionSchema = z.object({
  path: RegimePathSchema,
  incomeTaxDue: PesoSchema,
  percentageTaxDue: PesoSchema,
  totalTaxBurden: PesoSchema,
  label: z.string(),
  requiresDocumentation: z.boolean(),
  requiresOas: z.boolean(),
  effectiveRate: RateSchema,
});

// PercentageTaxResult
const PercentageTaxResultSchema = z.object({
  ptApplies: z.boolean(),
  ptRate: RateSchema,
  ptBase: PesoSchema,
  ptDue: PesoSchema,
  form2551qRequired: z.boolean(),
  filingDeadline: ISODateSchema.nullable(),
  reason: z.string(),
});

// PenaltyStack
const PenaltyStackSchema = z.object({
  surcharge: PesoSchema,
  interest: PesoSchema,
  compromise: PesoSchema,
  total: PesoSchema,
});

// PenaltyResult
const PenaltyResultSchema = z.object({
  applies: z.boolean(),
  daysLate: z.number().int(),
  monthsLate: z.number().int(),
  itPenalties: PenaltyStackSchema,
  ptPenalties: PenaltyStackSchema,
  totalPenalties: PesoSchema,
});

// ValidationWarning
const ValidationWarningSchema = z.object({
  code: z.string(),
  message: z.string(),
  severity: z.string(),
});

// ManualReviewFlag
const ManualReviewFlagSchema = z.object({
  code: z.string(),
  message: z.string(),
  field: z.string().nullable(),
});

// Form1701AOutput
const Form1701AOutputSchema = z.object({
  taxYearCovered: TaxYearSchema,
  amendedReturn: z.boolean(),
  shortPeriodReturn: z.boolean(),
  fiscalYearEnd: ISODateSchema.nullable(),
  tin: z.string(),
  rdoCode: z.string(),
  taxpayerNameLast: z.string(),
  taxpayerNameFirst: z.string(),
  taxpayerNameMiddle: z.string(),
  citizenship: z.string(),
  civilStatus: z.string(),
  registeredAddress: z.string(),
  zipCode: z.string(),
  contactNumber: z.string(),
  emailAddress: z.string(),
  businessName: z.string(),
  psicCode: z.string(),
  methodOfDeduction: z.string(),
  typeOfTaxpayer: z.string(),
  birthday: ISODateSchema,
  atcCode: z.string(),
  isAvailingOsd: z.boolean(),
  isAvailing8pct: z.boolean(),
  incomeTaxDue: PesoSchema,
  lessTaxRelief: PesoSchema,
  incomeTaxDueNetOfRelief: PesoSchema,
  addPenaltiesSurcharge: PesoSchema,
  addPenaltiesInterest: PesoSchema,
  addPenaltiesCompromise: PesoSchema,
  totalTaxPayable: PesoSchema,
  lessTaxCredits: PesoSchema,
  netTaxPayable: PesoSchema,
  overpayment: PesoSchema,
  overpaymentToBeRefunded: z.boolean(),
  overpaymentToBeIssuedTcc: z.boolean(),
  overpaymentToCarryOver: z.boolean(),
  cpaTin: z.string().nullable(),
  cpaName: z.string().nullable(),
  cpaAccreditationNumber: z.string().nullable(),
  ivaGrossSalesServices: PesoSchema,
  ivaSalesReturnsAllowances: PesoSchema,
  ivaNetSales: PesoSchema,
  ivaCostOfSales: PesoSchema,
  ivaTotalGrossIncome: PesoSchema,
  ivaNonOpIncomeInterest: PesoSchema,
  ivaNonOpIncomeRental: PesoSchema,
  ivaNonOpIncomeRoyalty: PesoSchema,
  ivaNonOpIncomeDividend: PesoSchema,
  ivaNonOpIncomeOthers: PesoSchema,
  ivaOsdAmount: PesoSchema,
  ivaNetTaxableIncome: PesoSchema,
  ivaGraduatedTaxTable1: PesoSchema,
  ivaGraduatedTaxTable2: PesoSchema,
  ivaIncomeTaxDue: PesoSchema,
  ivbGrossSalesServices: PesoSchema,
  ivbSalesReturnsAllowances: PesoSchema,
  ivbNetSales: PesoSchema,
  ivbNonOpIncomeInterest: PesoSchema,
  ivbNonOpIncomeRental: PesoSchema,
  ivbNonOpIncomeRoyalty: PesoSchema,
  ivbNonOpIncomeDividend: PesoSchema,
  ivbNonOpIncomeOthers: PesoSchema,
  ivbTotalGross: PesoSchema,
  ivbLess250k: PesoSchema,
  ivbTaxableIncome: PesoSchema,
  ivbIncomeTaxDue: PesoSchema,
  tcPriorYearExcess: PesoSchema,
  tcQuarterly1701qPayments: PesoSchema,
  tcCwtQ1Q2Q3: PesoSchema,
  tcCwtQ4: PesoSchema,
  tcPriorFilingPayment: PesoSchema,
  tcForeignTaxCredits: PesoSchema,
  tcOtherCredits: PesoSchema,
  tcTotalCredits: PesoSchema,
});

// NolcoScheduleRow
const NolcoScheduleRowSchema = z.object({
  colAYearIncurred: TaxYearSchema,
  colBOriginalLoss: PesoSchema,
  colCAppliedPriorYears: PesoSchema,
  colDBalanceBeginning: PesoSchema,
  colEAppliedCurrentYear: PesoSchema,
  colFBalanceEnd: PesoSchema,
  expiryYear: TaxYearSchema,
  expired: z.boolean(),
});

// Form1701Output
const Form1701OutputSchema = z.object({
  taxYearCovered: TaxYearSchema,
  amendedReturn: z.boolean(),
  shortPeriodReturn: z.boolean(),
  tin: z.string(),
  rdoCode: z.string(),
  taxpayerNameLast: z.string(),
  taxpayerNameFirst: z.string(),
  taxpayerNameMiddle: z.string(),
  citizenship: z.string(),
  civilStatus: z.string(),
  registeredAddress: z.string(),
  zipCode: z.string(),
  contactNumber: z.string(),
  emailAddress: z.string(),
  businessName: z.string(),
  psicCode: z.string(),
  methodOfDeduction: z.string(),
  typeOfTaxpayer: z.string(),
  birthday: ISODateSchema,
  atcCode: z.string(),
  withBusinessIncome: z.boolean(),
  withCompensationIncome: z.boolean(),
  incomeTaxDue: PesoSchema,
  lessTaxRelief: PesoSchema,
  netTaxDue: PesoSchema,
  surcharge: PesoSchema,
  interest: PesoSchema,
  compromise: PesoSchema,
  totalPayable: PesoSchema,
  lessTaxCreditsTotal: PesoSchema,
  netPayable: PesoSchema,
  overpaymentAmount: PesoSchema,
  overpaymentRefund: z.boolean(),
  overpaymentTcc: z.boolean(),
  overpaymentCarryOver: z.boolean(),
  secondInstallmentAmount: PesoSchema,
  sched2GrossCompensation: PesoSchema,
  sched2NonTaxableExclusions: PesoSchema,
  sched2TaxableCompensation: PesoSchema,
  sched3aGrossReceipts: PesoSchema,
  sched3aLessReturns: PesoSchema,
  sched3aNetReceipts: PesoSchema,
  sched3aLessCogs: PesoSchema,
  sched3aGrossIncomeFromOps: PesoSchema,
  sched3aNonOpIncome: PesoSchema,
  sched3aTotalGrossIncome: PesoSchema,
  sched3aDeductionMethod: z.string(),
  sched3aTotalDeductions: PesoSchema,
  sched3aCompNti: PesoSchema,
  sched3aBizNti: PesoSchema,
  sched3aTotalNti: PesoSchema,
  sched3aTaxTable1: PesoSchema,
  sched3aTaxTable2: PesoSchema,
  sched3aIncomeTaxDue: PesoSchema,
  sched3bGrossReceipts: PesoSchema,
  sched3bLessReturns: PesoSchema,
  sched3bNetReceipts: PesoSchema,
  sched3bNonOpIncome: PesoSchema,
  sched3bTotalGross: PesoSchema,
  sched3bLess250k: PesoSchema,
  sched3bTaxableIncome: PesoSchema,
  sched3bIncomeTaxDue: PesoSchema,
  sched4CompensationDeductions: PesoSchema,
  sched4SssGsisPhilhealth: PesoSchema,
  sched4Rent: PesoSchema,
  sched4Interest: PesoSchema,
  sched4Utilities: PesoSchema,
  sched4Ear: PesoSchema,
  sched4Communication: PesoSchema,
  sched4Depreciation: PesoSchema,
  sched4TaxesLicenses: PesoSchema,
  sched4Insurance: PesoSchema,
  sched4ProfessionalFees: PesoSchema,
  sched4Travel: PesoSchema,
  sched4Supplies: PesoSchema,
  sched4Charitable: PesoSchema,
  sched4BadDebts: PesoSchema,
  sched4ResearchDevelopment: PesoSchema,
  sched4Others: PesoSchema,
  sched4TotalOrdinaryDeductions: PesoSchema,
  sched5PensionTrust: PesoSchema,
  sched5PremiumHealthHospitalization: PesoSchema,
  sched5Nolco: PesoSchema,
  sched5FringeBenefits: PesoSchema,
  sched5Total: PesoSchema,
  sched6Entries: z.array(NolcoScheduleRowSchema),
  v1TaxOnComp: PesoSchema,
  v2TaxFromSched3aOr3b: PesoSchema,
  v3LessSpecialDeductions: PesoSchema,
  v4TotalTax: PesoSchema,
  v5IncomeTaxDue: PesoSchema,
  vi1PriorYearExcess: PesoSchema,
  vi2Q1Payment: PesoSchema,
  vi3Q2Payment: PesoSchema,
  vi4Q3Payment: PesoSchema,
  vi5CwtQ1Q2Q3: PesoSchema,
  vi6CwtQ4: PesoSchema,
  vi7CompCwt: PesoSchema,
  vi8PriorAmendedPayment: PesoSchema,
  vi9ForeignTaxCredit: PesoSchema,
  vi10OtherCredits: PesoSchema,
  vi11TotalCredits: PesoSchema,
  vi12NetTaxPayable: PesoSchema,
});

// Form1701QOutput
const Form1701QOutputSchema = z.object({
  taxYear: TaxYearSchema,
  quarter: QuarterSchema,
  returnPeriodFrom: ISODateSchema,
  returnPeriodTo: ISODateSchema,
  amendedReturn: z.boolean(),
  tin: z.string(),
  rdoCode: z.string(),
  taxpayerName: z.string(),
  businessName: z.string(),
  siGrossReceipts: PesoSchema,
  siLessReturns: PesoSchema,
  siNetReceipts: PesoSchema,
  siLessCogs: PesoSchema,
  siGrossIncome: PesoSchema,
  siNonOpIncome: PesoSchema,
  siTotalGrossIncome: PesoSchema,
  siDeductions: PesoSchema,
  siPriorQtrNti: PesoSchema,
  siTotalNti: PesoSchema,
  siIncomeTaxDueTable1: PesoSchema,
  siIncomeTaxDueTable2: PesoSchema,
  siIncomeTaxDue: PesoSchema,
  siiCurrentQtrGross: PesoSchema,
  siiReturnsAllowances: PesoSchema,
  siiNetCurrent: PesoSchema,
  siiPriorQtrCumulative8pct: PesoSchema,
  siiTotalCumulativeGross: PesoSchema,
  siiLess250k: PesoSchema,
  siiTaxableCumulative: PesoSchema,
  siiTaxDue8pct: PesoSchema,
  siiiCwtCurrentQuarter: PesoSchema,
  siiiPriorQtrCwtAlreadyClaimed: PesoSchema,
  siiiNetCwtThisQtr: PesoSchema,
  siiiPriorQtr1701qPayments: PesoSchema,
  siiiPriorYearExcess: PesoSchema,
  siiiTotalCredits: PesoSchema,
  siiiNetPayable: PesoSchema,
  sivSurcharge: PesoSchema,
  sivInterest: PesoSchema,
  sivCompromise: PesoSchema,
  sivTotalPenalties: PesoSchema,
});

// PT2551QScheduleRow
const PT2551QScheduleRowSchema = z.object({
  atcCode: z.string(),
  taxBase: PesoSchema,
  rate: RateSchema,
  taxDue: PesoSchema,
  description: z.string(),
});

// Form2551QOutput
const Form2551QOutputSchema = z.object({
  taxYear: TaxYearSchema,
  quarter: QuarterOr4Schema,
  returnPeriodFrom: ISODateSchema,
  returnPeriodTo: ISODateSchema,
  amendedReturn: z.boolean(),
  nilReturn: z.boolean(),
  tin: z.string(),
  rdoCode: z.string(),
  taxpayerName: z.string(),
  businessName: z.string(),
  atcCode: z.string(),
  grossTaxableSalesReceipts: PesoSchema,
  percentageTaxRate: RateSchema,
  percentageTaxDue: PesoSchema,
  lessPtCwtCredits: PesoSchema,
  netPtPayable: PesoSchema,
  addSurcharge: PesoSchema,
  addInterest: PesoSchema,
  addCompromise: PesoSchema,
  totalAmountPayable: PesoSchema,
  schedule1Rows: z.array(PT2551QScheduleRowSchema),
});

// FormOutputUnion — adjacently tagged discriminated union
const FormOutputUnionSchema = z.discriminatedUnion('formVariant', [
  z.object({ formVariant: z.literal('Form1701'), fields: Form1701OutputSchema }),
  z.object({ formVariant: z.literal('Form1701a'), fields: Form1701AOutputSchema }),
  z.object({ formVariant: z.literal('Form1701q'), fields: Form1701QOutputSchema }),
]);

// TaxComputationResultSchema — no .strict() (output, forward compatible)
export const TaxComputationResultSchema = z.object({
  inputSummary: InputSummarySchema,
  comparison: z.array(RegimeOptionSchema),
  recommendedRegime: RegimePathSchema,
  usingLockedRegime: z.boolean(),
  savingsVsWorst: PesoSchema,
  savingsVsNextBest: PesoSchema,
  selectedPath: RegimePathSchema,
  selectedIncomeTaxDue: PesoSchema,
  selectedPercentageTaxDue: PesoSchema,
  selectedTotalTax: PesoSchema,
  pathADetails: PathAResultSchema.nullable(),
  pathBDetails: PathBResultSchema.nullable(),
  pathCDetails: PathCResultSchema.nullable(),
  grossAggregates: GrossAggregatesSchema,
  totalItCredits: PesoSchema,
  cwtCredits: PesoSchema,
  quarterlyPayments: PesoSchema,
  priorYearExcess: PesoSchema,
  compensationCwt: PesoSchema,
  balance: PesoSchema,
  disposition: BalanceDispositionSchema,
  overpayment: PesoSchema,
  overpaymentDisposition: OverpaymentDispositionSchema.nullable(),
  installmentEligible: z.boolean(),
  installmentFirstDue: PesoSchema,
  installmentSecondDue: PesoSchema,
  ptResult: PercentageTaxResultSchema,
  formType: FormTypeSchema,
  formOutput: FormOutputUnionSchema,
  ptFormOutput: Form2551QOutputSchema.nullable(),
  requiredAttachments: z.array(z.string()),
  penalties: PenaltyResultSchema.nullable(),
  manualReviewFlags: z.array(ManualReviewFlagSchema),
  warnings: z.array(ValidationWarningSchema),
  engineVersion: z.string(),
  computedAt: ISODateSchema,
});

export type TaxComputationResultInput = z.input<typeof TaxComputationResultSchema>;
