/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthProjectsIndexRouteImport } from './routes/_auth/projects/index'
import { Route as AuthInventoryIndexRouteImport } from './routes/_auth/inventory/index'
import { Route as AuthFinancialsIndexRouteImport } from './routes/_auth/financials/index'
import { Route as AuthProjectsNewRouteImport } from './routes/_auth/projects/new'
import { Route as AuthProjectsProjectIdProcurementRouteImport } from './routes/_auth/projects/$projectId/procurement'
import { Route as AuthProjectsProjectIdIntakeRouteImport } from './routes/_auth/projects/$projectId/intake'
import { Route as AuthProjectsProjectIdFinancialsRouteImport } from './routes/_auth/projects/$projectId/financials'
import { Route as AuthProjectsProjectIdDeploymentRouteImport } from './routes/_auth/projects/$projectId/deployment'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthProjectsIndexRoute = AuthProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthInventoryIndexRoute = AuthInventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthFinancialsIndexRoute = AuthFinancialsIndexRouteImport.update({
  id: '/financials/',
  path: '/financials/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProjectsNewRoute = AuthProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProjectsProjectIdProcurementRoute =
  AuthProjectsProjectIdProcurementRouteImport.update({
    id: '/projects/$projectId/procurement',
    path: '/projects/$projectId/procurement',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthProjectsProjectIdIntakeRoute =
  AuthProjectsProjectIdIntakeRouteImport.update({
    id: '/projects/$projectId/intake',
    path: '/projects/$projectId/intake',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthProjectsProjectIdFinancialsRoute =
  AuthProjectsProjectIdFinancialsRouteImport.update({
    id: '/projects/$projectId/financials',
    path: '/projects/$projectId/financials',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthProjectsProjectIdDeploymentRoute =
  AuthProjectsProjectIdDeploymentRouteImport.update({
    id: '/projects/$projectId/deployment',
    path: '/projects/$projectId/deployment',
    getParentRoute: () => AuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/projects/new': typeof AuthProjectsNewRoute
  '/financials/': typeof AuthFinancialsIndexRoute
  '/inventory/': typeof AuthInventoryIndexRoute
  '/projects/': typeof AuthProjectsIndexRoute
  '/projects/$projectId/deployment': typeof AuthProjectsProjectIdDeploymentRoute
  '/projects/$projectId/financials': typeof AuthProjectsProjectIdFinancialsRoute
  '/projects/$projectId/intake': typeof AuthProjectsProjectIdIntakeRoute
  '/projects/$projectId/procurement': typeof AuthProjectsProjectIdProcurementRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/projects/new': typeof AuthProjectsNewRoute
  '/financials': typeof AuthFinancialsIndexRoute
  '/inventory': typeof AuthInventoryIndexRoute
  '/projects': typeof AuthProjectsIndexRoute
  '/projects/$projectId/deployment': typeof AuthProjectsProjectIdDeploymentRoute
  '/projects/$projectId/financials': typeof AuthProjectsProjectIdFinancialsRoute
  '/projects/$projectId/intake': typeof AuthProjectsProjectIdIntakeRoute
  '/projects/$projectId/procurement': typeof AuthProjectsProjectIdProcurementRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_auth/projects/new': typeof AuthProjectsNewRoute
  '/_auth/financials/': typeof AuthFinancialsIndexRoute
  '/_auth/inventory/': typeof AuthInventoryIndexRoute
  '/_auth/projects/': typeof AuthProjectsIndexRoute
  '/_auth/projects/$projectId/deployment': typeof AuthProjectsProjectIdDeploymentRoute
  '/_auth/projects/$projectId/financials': typeof AuthProjectsProjectIdFinancialsRoute
  '/_auth/projects/$projectId/intake': typeof AuthProjectsProjectIdIntakeRoute
  '/_auth/projects/$projectId/procurement': typeof AuthProjectsProjectIdProcurementRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/auth/callback'
    | '/projects/new'
    | '/financials/'
    | '/inventory/'
    | '/projects/'
    | '/projects/$projectId/deployment'
    | '/projects/$projectId/financials'
    | '/projects/$projectId/intake'
    | '/projects/$projectId/procurement'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/auth/callback'
    | '/projects/new'
    | '/financials'
    | '/inventory'
    | '/projects'
    | '/projects/$projectId/deployment'
    | '/projects/$projectId/financials'
    | '/projects/$projectId/intake'
    | '/projects/$projectId/procurement'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/auth/callback'
    | '/_auth/projects/new'
    | '/_auth/financials/'
    | '/_auth/inventory/'
    | '/_auth/projects/'
    | '/_auth/projects/$projectId/deployment'
    | '/_auth/projects/$projectId/financials'
    | '/_auth/projects/$projectId/intake'
    | '/_auth/projects/$projectId/procurement'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/projects/': {
      id: '/_auth/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthProjectsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/inventory/': {
      id: '/_auth/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AuthInventoryIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/financials/': {
      id: '/_auth/financials/'
      path: '/financials'
      fullPath: '/financials/'
      preLoaderRoute: typeof AuthFinancialsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/projects/new': {
      id: '/_auth/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof AuthProjectsNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/projects/$projectId/procurement': {
      id: '/_auth/projects/$projectId/procurement'
      path: '/projects/$projectId/procurement'
      fullPath: '/projects/$projectId/procurement'
      preLoaderRoute: typeof AuthProjectsProjectIdProcurementRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/projects/$projectId/intake': {
      id: '/_auth/projects/$projectId/intake'
      path: '/projects/$projectId/intake'
      fullPath: '/projects/$projectId/intake'
      preLoaderRoute: typeof AuthProjectsProjectIdIntakeRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/projects/$projectId/financials': {
      id: '/_auth/projects/$projectId/financials'
      path: '/projects/$projectId/financials'
      fullPath: '/projects/$projectId/financials'
      preLoaderRoute: typeof AuthProjectsProjectIdFinancialsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/projects/$projectId/deployment': {
      id: '/_auth/projects/$projectId/deployment'
      path: '/projects/$projectId/deployment'
      fullPath: '/projects/$projectId/deployment'
      preLoaderRoute: typeof AuthProjectsProjectIdDeploymentRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthProjectsNewRoute: typeof AuthProjectsNewRoute
  AuthFinancialsIndexRoute: typeof AuthFinancialsIndexRoute
  AuthInventoryIndexRoute: typeof AuthInventoryIndexRoute
  AuthProjectsIndexRoute: typeof AuthProjectsIndexRoute
  AuthProjectsProjectIdDeploymentRoute: typeof AuthProjectsProjectIdDeploymentRoute
  AuthProjectsProjectIdFinancialsRoute: typeof AuthProjectsProjectIdFinancialsRoute
  AuthProjectsProjectIdIntakeRoute: typeof AuthProjectsProjectIdIntakeRoute
  AuthProjectsProjectIdProcurementRoute: typeof AuthProjectsProjectIdProcurementRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthProjectsNewRoute: AuthProjectsNewRoute,
  AuthFinancialsIndexRoute: AuthFinancialsIndexRoute,
  AuthInventoryIndexRoute: AuthInventoryIndexRoute,
  AuthProjectsIndexRoute: AuthProjectsIndexRoute,
  AuthProjectsProjectIdDeploymentRoute: AuthProjectsProjectIdDeploymentRoute,
  AuthProjectsProjectIdFinancialsRoute: AuthProjectsProjectIdFinancialsRoute,
  AuthProjectsProjectIdIntakeRoute: AuthProjectsProjectIdIntakeRoute,
  AuthProjectsProjectIdProcurementRoute: AuthProjectsProjectIdProcurementRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
