/**
 * Stub module for the Rust/WASM inheritance engine.
 * The real module is generated by `wasm-pack build` in the Rust engine package.
 * This stub allows the frontend to build without the compiled WASM artifact.
 */

export function initSync(_input) {
  // No-op: WASM binary not available in this build
}

export function compute_json(_input) {
  throw new Error('WASM engine not available. Run `wasm-pack build` in the Rust engine package.');
}

export default async function init() {
  // No-op: WASM binary not available in this build
}
