/**
 * Type declarations for the compiled Rust/WASM inheritance engine.
 * The actual .wasm file and JS glue are generated by wasm-pack at build time.
 */

/** Synchronous initialization (Node.js / test environments). */
export function initSync(input: { module: BufferSource }): void;

/** Compute inheritance distribution; input/output are JSON strings. */
export function compute_json(input: string): string;

/** Default export: async initialization for browser environments. */
declare function init(): Promise<void>;
export default init;
